apiVersion: v1
kind: Service
metadata:
  name: my-service-fastapiapp
  namespace: webapp
  annotations:
     metallb.io/address-pool: ippool-addresses
     metallb.io/allow-shared-ip: "my-shared-ip-key"
     metallb.io/loadBalancerIPs: "192.168.254.214"
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8000
